spring.application.name=SecuringJobApp
spring.datasource.url=jdbc:postgresql://localhost:5432/Telusko
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Default server port
server.port=8080
